### ISSUE TITLE
Docker build failed due to missing maven-surefire-plugin

### ISSUE THREAD

**Issue by skydiator** [L21s/nexus3-github-oauth-plugin#48]
Build command: **mvn -f pom.xml clean package**

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:25 min
[INFO] Finished at: 2020-09-23T17:41:46Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project nexus3-github-oauth-plugin: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /usr/src/app && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx300M -XX:MaxDirectMemorySize=2G -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/src/app/target/surefire-reports -jar /usr/src/app/target/surefire/surefirebooter8300039441140651742.jar /usr/src/app/target/surefire/surefire2557217196044690055tmp /usr/src/app/target/surefire/surefire_05653415476508086405tmp
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
The command '/bin/sh -c mvn -f /usr/src/app/pom.xml clean package' returned a non-zero code: 1

What I did to resolve the above issue is to update the pom.xml to include the following:
>             <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-surefire-plugin</artifactId>
>             <configuration>
>                 <useSystemClassLoader>false</useSystemClassLoader>
>             </configuration>
>             </plugin>

I'm not sure if this is a known issue. If not, want me to put this in a PR?

**Comment by tobilarscheid** [comment]
`docker build . ` works fine when cloning the latest master
